apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: astro-app-build-run
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/task: "[git-clone, buildah]"
  labels:
    app.kubernetes.io/instance: astro-app
    backstage.io/kubernetes-id: astro-app
spec:
  pipelineSpec:
    params:
      - name: repo-url
        type: string
      - name: revision
        type: string
      - name: image
        type: string
        default: quay.io/jefrankl/astro-app:latest
    workspaces:
      - name: source
      - name: dockerconfig
    tasks:
      - name: clone
        taskRef:
          name: git-clone
        params:
          - name: url
            value: $(params.repo-url)
          - name: revision
            value: $(params.revision)
        workspaces:
          - name: output
            workspace: source
      - name: build-app
        runAfter: [clone]
        taskSpec:
          metadata: {}
          spec: null
          workspaces:
            - name: source
          steps:
            - name: npm-install
              computeResources: {}
              image: registry.access.redhat.com/ubi9/nodejs-22:latest
              workingDir: $(workspaces.source.path)
              script: |
                npm install
                npm run build
        workspaces:
          - name: source
            workspace: source
      - name: build-image
        runAfter: [build-app]
        taskRef:
          name: buildah
        params:
          - name: IMAGE
            value: $(params.image)
        workspaces:
          - name: source
            workspace: source
          - name: dockerconfig
            workspace: dockerconfig
  params:
    - name: repo-url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: dockerconfig
      secret:
        secretName: quay-push-credentials
